name: Auto Update ECS

on:
  push:
    branches:
      - main

jobs:
  update-ecs:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH into ECS and pull changes
      run: |
        sshpass -p ${{ secrets.ECS_PASSWORD }} ssh ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_HOST }} -p ${{ secrets.ECS_SSH_PORT }} 'cd /var/www/bengkel-cat-w && git pull'
